### ISSUE TITLE
Missing resource mapping in netweaver config

### ISSUE THREAD

**Issue by marcelschork** [mauriciolauffer/ui5-deployer#19]
Hi @mauriciolauffer ,
thanks for the hint regarding #18 . The deployment was indeed successful, but I faced another issue 
```yaml
specVersion: '2.2'
metadata:
  name: ui5-showcase-app
type: application
customConfiguration:
  deployer:
    type: sap-netweaver
    sourcePath: dist/
    connection:
      url: https://sap.system.com
      strictSSL: false
    abapRepository:
      client: 100
      language: DE
      package: $TMP
      bspApplication: Z_UI5_SHOWCASE
      bspApplicationText: UI5 Showcase app
      appIndexCalculate: true
      skipAdtValidations: true
```
![deploy_error](https://user-images.githubusercontent.com/63337737/108813999-5e339780-75b2-11eb-862a-3d512e68549a.png)
The folder structure looks like follows

```
test
  -- dist
      -- Component-preload.js
      -- ...
  -- package.json
  -- ui5.yaml
```
The problem is the missing resource mapping in the yaml file
```yaml
resources:
  configuration:
    paths:
      webapp: dist
```
I guess the sample for SAP Netweaver needs an update here or should it work without explicit resource mapping?

Best regards,
Marcel
