### ISSUE TITLE
CSRF token validation failed

### ISSUE THREAD

**Issue by VGordillo-Resulto** [mauriciolauffer/ui5-deployer#23]
Hi @mauriciolauffer,

We need to deploy a fairly large application, having a Component-preload.js file with a size of 30MB.
After almost an hour trying to deploy it, I have received that error.

![image](https://user-images.githubusercontent.com/65761949/116999729-51cd6880-ace0-11eb-9220-9002d62fd667.png)

```
customConfiguration:
  deployer:
    type: sap-netweaver
    sourcePath: dist/
    connection:
      url: https://**********.com:8081
      strictSSL: false
      SSLCertificatePath: **********cer
    credentials:
      username: **********
      password: **********
    abapRepository:
      client: 100
      language: EN
      transportRequest: **********
      package: **********
      bspApplication: **********
      bspApplicationText: **********
      skipAdtValidations: true
      appIndexCalculate: false
```
